resourceGroup = "myAssignment"
managedIdentityAcr = "containerappmidentity"
location = "westeurope"
myContainerRegistry= "exodusacr"
myContainerApp= "mycontainerappname"
myLogAnalytics= "myloganalyticsname"
