resourceGroup = "myAssignmentrg"
managedIdentityAcr = "containerappmidentity"
location = "westeurope"
myContainerRegistry= "exodusacr"
myContainerApp= "mycontainerappname"
myLogAnalytics= "myloganalyticsname"
myContainerAppEnv= "mycontainerappenv"
